services:
  adminContext:
      class:  Youshido\AdminBundle\Service\AdminContext
      arguments: [@service_container]

  adminExcelExporter:
      class: Youshido\AdminBundle\Service\ExcelExporter
      calls:
          - [setContainer, [@service_container] ]

  app.twig_extension:
      class: Youshido\AdminBundle\Twig\AdminExtension
      public: true
      calls:
          - [ setContainer, [@service_container]]
      tags:
          - { name: twig.extension }